config/routes.rb
Rails.application.routes.draw do
  # get "up" => "rails/health#show", as: :rails_health_check

  root "pages#home"
  get "/about", to: "pages#about"
  resources :articles, only: [ :show, :index, :new, :create, :edit, :update, :destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { minimum: 6, maxmimum: 100 }
  validates :description, presence: true, length: { minimum: 10, maxmimum: 300 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]
  def index
    @articles = Article.all
  end
  def show
    # @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:notice] = "Article was created successfully."
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    # @article = Article.find(params[:id])
  end

  def update
    # @article = Article.find(params[:id])
    if @article.update(article_params)
      flash[:notice] = "Article was updated successfully"
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :description)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<%=form_with model: article do |form|%>
        <p>
            <%= form.label :title %>
            
        </p>
        <p>
            <%= form.text_field :title %>
        </p>

        <p>
            <%= form.label :description %>
        </p>
        <p>
            <%= form.text_area :description %>
        </p>

        <p>
            <%= form.submit @article.persisted? ? "Update Article" : "Save Article" %>
        </p>
<%end%>

app/views/articles/edit.html.erb
<h1><%= @article.title %></h1>

<%= render "form", article: @article%>
<p>
    <%= link_to "Cancel", @article %>
</p>

app/views/articles/index.html.erb
<h1>Articles listing page</h1>

<p>
    <%= link_to "New article", new_article_path %>
</p>

<table>
    <thead>
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th colspan="3">Action</th>
        </tr>
    </thead>
    <tbody>
        <% @articles.each do |article| %>
        <tr>
            <td><%= article.title%></td>
            <td><%= article.description%></td>
            <td><%= link_to "Show", article_path(article)%></td>
            <td><%= link_to "Edit", edit_article_path(article)%></td>
            <td><%= button_to "Delete", article, method: :delete, data: {turbo_confirm: "
            Are you Sure ?"}%></td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/articles/new.html.erb
<h1> New article </h1>

<% if @article.errors.any? %>
    <h2> The following errors prevented the article from being saved </h2>
    <ul>
        <% @article.errors.full_messages.each do |msg| %>
            <li> <%= msg %> </li>
        <% end %>
    </ul>
   
<% end %>
<%= render "form", article: @article%>
<p> 
    <%= link_to "Return to articles listing", articles_path%>
</p>

app/views/articles/show.html.erb
<h1> Article Detail</h1>

<p>
    <strong>Title: </strong><%= @article.title%>
</p>
<p>
    <strong>Description: </strong><%= @article.description%>
</p>
<p>
    <%= link_to "Return to articles listing", articles_path%> |
    <%= link_to "Edit", edit_article_path(@article)%>
    <%= button_to "Delete", @article, method: :delete, data: { turbo_confirm: "
    Are you sure? " } %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Fun Blog" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do | name, msg|%>
      <%= msg %>
    <%end%>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Welcome to the About page </h1>

<%= link_to "Articles listing", articles_path %> |
<%= link_to "Home page", root_path %>

app/views/pages/home.html.erb
<div class="center jumbotron">
    <h1> Welcome to the Homepage </h1>
</div>

<%= link_to "Articles listing", articles_path %> |
<%= link_to "About page", about_path %>